# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers
toe_foot_position_controller:
  type: effort_controllers/JointPositionController
  joint: toe_foot_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
foot_leg_position_controller:
  type: effort_controllers/JointPositionController
  joint: foot_leg_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}